version: '3.8'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app
    ports:
      - "80:80"
    depends_on:

      - postgresql

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      ## - ./docker/php-configuration:/usr/local/etc/php
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    depends_on:
      - nginx

  php-cli:
    build:
      context: docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      ##- ./docker/php-configuration:/usr/local/etc/php
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password

  postgresql:
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_USER: app
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
